sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '0.12'
  - v4
  - stable
after_success:
  - 'travis-after-all && npm run semantic-release'
env:
  global:
    - secure: U60ZCL0C6j19MO0Rv/zrqqx0TnFj5nrpPv6A61xU5ilhz9M8aL7mGoUOEyMVtr0NF3wEExSjAqCdWzZBdlyYhvteJzGeUCmBEQOF0TARb79sBF3gOxRzWnKmYJy2XiVNGLuzx70glqPDS/q70FBbE9mR54vj64dcVTKmmZ8grj2CXFN+rD4PanNs4BU3+CxQM86iYeH5BprAt7YW6eAKUxdAv9co3vaer/RdHR9h8U49qcbOFqXWg3yBQETqOM3i0mN5r4DCxUGeWr0hBdHgynpYLVzLS5woe55pXgwkF3j7rRkowukSPTUJ7OMs/BnOVkHvVlQnSqwbZzKXxo1qm1J10eCqqMMg/t/5GDRV7oNSD0gu/hM7xiZPz3EQcZ+v0RpO5Nit1dn4sjaChVVVnZ9+hcoxkXgOhhOxEn9qA/aVvbyGnDku411W/SlGXLvgspCE3fFr9c6ii2LDjqFlBzX3LBiT26XWsDjT3hvmFjOKFl3AB5uBsKSxFO0bq7wlwHE2liMKuEudQWfFafuLdZtcIJvcT9zhMVPbzXvjCKj0yChMadIFJv/M0EUF0gDgz/5h8Df+rE+IP4JsS6uZTEGE5WHROTylQ9XUdZE4G3e2qv/zhRt3hzigEuCjej8Mv+zeVI/A8EN8o7z0y5HPdSEqkXglmpTme1/7PeaidoA=
    - secure: HgyTkddfOFE6y3CSoDF51xU5NOrOLvqv1sQvSIEKRInba40g6btQGlLH3eMtLWs4UTmoL3wIttm43/iXx1ZNdsvxJssOaxM3LTVS5eN8bIXxXi262EQI5cxORpOqtDQkE4weFB0Htj25CUWFEY7lJea7/ndFL2tQaPL5CfWGFiKudLGgv3TG/QOim8gset3Mi6imEleerqCrQ9lV2A8sAV+qK1x0g5V1TB2sMOWQCaZiWoUCDir4pvjr2DHHHk0+2/3+40V5D71buZLRFNjrMN9blBoTh+CagxLlEIxGgXOzeYysZBUXSX72/2HfhypaaqqsWSfUkG5JO9qWJohcRgKgD6fq/huhfG5gpjU5B+jjPuOYJhXVRytnD87Kk37c17nhJON43cQJ/tFn45dO1eTf/NKN3RnkmEy9k62onQPpyRU48em7K+M3NDcFJevVBrOgIV8wRyZY7Bdx2yFRIXz3OjXBIHMoi1A2hIy0jbdoIuv6hQVUYMlldbt5kZ+WzArWZw+Y/i0B8uXRbx3zzrBUGcNvzsZDvXoGuBfmB0YZ1RcGT+fpucrYXVOqu/jO8pk/SQwsh+kEOD5VtNMCiK6g2CiS+KC1Y3Y/3sZ5ZLC06Tf4w+axXhBJqrOq77ZfxyO84ye50TRbcXqZGvgC3G2YSvSoPU7eOzHVky6IdiE=
